#01
import math
print('DIGITE UM NUMERO: ')
num=float(input('   '))
print('O valor digitado foi {}, e sua por ção inteuira é {}'.format(num,math.trunc(num)))

#02
from math import trunc
print('DIGITE UM NUMERO: ')
num=float(input('   '))
print('O valor digitado foi {}, e sua por ção inteuira é {}'.format(num,trunc(num)))

#03
print('DIGITE UM NUMERO: ')
num=float(input('   '))
print('O valor digitado foi {}, e sua por ção inteuira é {}'.format(num,int(num)))
